### PR TITLE
Improve Huszar Comparisons

### PR DESCRIPTION
**Pull request by garrettmflynn**
Added a few improvements to the previous comparison code. 

1. For some reason, I wasn't able to use `tqdm` in the notebook, so those function calls were removed
2. I cleaned up my directory structure and moved some of the folder setup earlier to a single cell
3. Based on @h-mayorquin's question in #57, I am printing a message if a file is unreadable rather than filtering out files prepended with a `.`.

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
> For some reason, I wasn't able to use tqdm in the notebook,

You can replace with `from tqdm.notebook import tqdm`, usually aliased using `as tqdm_notebook` to avoid namespace clashes

**Review by h-mayorquin — CHANGES_REQUESTED** [review]
Looks good me. Can you run your notebook without output and then commit the notebook in that state. I don't know how you use notebooks but there is usually an option "clear all outputs" in the top. I am having difficulties with the merge on my side and I think this will make it easier.

**Comment by h-mayorquin** [comment]
Actually, let's merge it like this because otherwise you will have a diff problem with master. I will take care of fixing this.

**Comment by garrettmflynn** [comment]
Thanks @h-mayorquin. I'll keep this in mind moving forward

**Pull request merged**
